### PR TITLE
Add compare

### PR DESCRIPTION
**Pull request by derekriemer**

### CODE REVIEW

**Comment by derekriemer** [comment]
Um, what? there's some weird changes here.

**Comment by derekriemer** [comment]
All good. I forgot to pull before creating the branch, and tried to undo my earlier change.

**Review by jcsteh — CHANGES_REQUESTED** [review]
Thanks for the PR.

For future reference, please include a clear explanation of the change in the commit/PR; e.g. "GitHub: Add headings for comments on compare pages." or "GitHub: Add headings for changed files on compare pages." Sure, we had a discussion about this, but if I come to it in future, I might not remember. Also, in this case, I'm not actually certain of your intent anyway; see comment below. Finally, it's good for historical purposes to have good explanations in PRs/commits.

**Comment by jcsteh** [comment]
Bleh. GitHub seems to have squelched my line comment when I was messing with the review summary.

Are you sure this block is the one you actually wanted to change? Did it have the intended effect? I thought you were saying you wanted to add headings for the file headers (which is another block later in the code). This block is for comments... but I'm guessing compare pages don't have comments. Also, please ensure you update the comment inside the block you change.

**Comment by jcsteh** [comment]
@DerekRiemer, do you intend to continue work on this? There are outstanding review actions; see https://github.com/nvaccess/axSGrease/pull/8#pullrequestreview-16057502 and https://github.com/nvaccess/axSGrease/pull/8#issuecomment-271759834.

**Pull request closed without merging**
